const cartItems = [
    {
        canteenName:"Red canteen",
        orderedFood : [
            {
                foodName:"Dosa",
                foodImg:'https://www.vegrecipesofindia.com/wp-content/uploads/2021/06/idli-recipe-4-500x500.jpg',
                quantity:1,
                price:"50",
            },
            {
                foodName:"Idly",
                foodImg:"https://www.cookwithmanali.com/wp-content/uploads/2020/05/Masala-Dosa.jpg",
                quantity:1,
                price:"30",
            },
            {
                foodName:"Vada",
                foodImg:"https://c.ndtvimg.com/2023-09/u113o4r_medu-vada_625x300_06_September_23.jpg",
                quantity:1,
                price:"20",
            },
            {
                foodName:"Vada",
                foodImg:"https://c.ndtvimg.com/2023-09/u113o4r_medu-vada_625x300_06_September_23.jpg",
                quantity:1,
                price:"20",
            },
            {
                foodName:"Vada",
                foodImg:"https://c.ndtvimg.com/2023-09/u113o4r_medu-vada_625x300_06_September_23.jpg",
                quantity:1,
                price:"20",
            },
            {
                foodName:"Vada",
                foodImg:"https://c.ndtvimg.com/2023-09/u113o4r_medu-vada_625x300_06_September_23.jpg",
                quantity:1,
                price:"20",
            },
            {
                foodName:"Vada",
                foodImg:"https://c.ndtvimg.com/2023-09/u113o4r_medu-vada_625x300_06_September_23.jpg",
                quantity:1,
                price:"20",
            },
            {
                foodName:"Vada",
                foodImg:"https://c.ndtvimg.com/2023-09/u113o4r_medu-vada_625x300_06_September_23.jpg",
                quantity:1,
                price:"20",
            },
            {
                foodName:"Vada",
                foodImg:"https://c.ndtvimg.com/2023-09/u113o4r_medu-vada_625x300_06_September_23.jpg",
                quantity:1,
                price:"20",
            },
        ],
    },
    {
        canteenName:"Green canteen",
        orderedFood : [
            {
                foodName:"Dosa",
                foodImg:'https://www.vegrecipesofindia.com/wp-content/uploads/2021/06/idli-recipe-4-500x500.jpg',
                quantity:1,
                price:"30",
            },
            {
                foodName:"Tea",
                foodImg:"https://assets.cntraveller.in/photos/60ba2522c28d168a1ec862a3/4:3/w_1440,h_1080,c_limit/Tea-.jpg",
                quantity:2,
                price:"13",
            },
        ],
    },
]

export default cartItems;